from __future__ import annotations

from typing import Any, Dict, List


def _base_constraints() -> List[str]:
    return [
        "Do NOT fabricate executed test results, approvals/signatures, meeting attendance, dates of completion, or audit outcomes.",
        "Do NOT make compliance claims (e.g., 'compliant', 'meets ISO/FDA requirements') or pass/fail conclusions.",
        "If required information is missing, keep explicit placeholders (e.g., 'TBD') and state what is missing.",
        "Keep the tone professional, audit-friendly, and clearly labeled as a draft example.",
    ]


def _compile_only_constraints() -> List[str]:
    return [
        "This document type is compile-only in SmartQS. Do NOT invent evidence-based content.",
        "Only propose a structure and placeholders, and explicitly state that the authoritative content is generated by compilation of existing artifacts.",
        "Do NOT imply that referenced artifacts exist; use conditional language (e.g., 'If Hazard Analysis exists, reference it here.').",
    ]


def get_document_ai_prompt_registry() -> Dict[str, Dict[str, Any]]:
    """
    Document-type prompt registry for AI example generation.

    Each entry is intentionally small and audit-safe:
    - purpose: what the doc is for
    - required_sections: must-have headings/sections
    - constraints: safety constraints (no compliance claims, no fake execution)
    - style: formatting expectations
    """
    base_constraints = _base_constraints()

    # RMF has a dedicated entry below (reference-only narrative if LLM is used elsewhere).
    compile_only = {"essential_requirements_checklist", "submission_index", "audit_package"}

    reg: Dict[str, Dict[str, Any]] = {
        "_default": {
            "purpose": "Provide a draft example structure for this SmartQS document type using the project setup context.",
            "required_sections": [
                "AI-GENERATED EXAMPLE — DRAFT ONLY",
                "Purpose",
                "Inputs (what data this draft used)",
                "Draft content (with placeholders)",
                "Open items / To be completed",
            ],
            "constraints": base_constraints,
            "style": [
                "Use clear headings and bullet lists where appropriate.",
                "Prefer concise, professional language.",
                "Keep placeholders explicit (TBD / Not provided).",
            ],
        },
        "rmp": {
            "purpose": "Risk Management Plan (RMP): defines risk management scope, roles, methods, and planned activities for the project.",
            "required_sections": [
                "Scope and intended use context",
                "Roles and responsibilities (placeholders; no approvals)",
                "Risk management process overview (ISO 14971-oriented, no claims)",
                "Risk acceptability approach (placeholder thresholds)",
                "Planned deliverables and reviews (placeholders)",
            ],
            "constraints": base_constraints,
            "style": ["Neutral, audit-friendly regulatory tone.", "No completion language; keep as planned."],
        },
        "hazard_analysis": {
            "purpose": "Hazard Analysis: identify hazards/hazardous situations relevant to the device and use context.",
            "required_sections": [
                "Assumptions and scope",
                "Hazard categories (seeded, draft)",
                "Draft hazard list/table (no risk scoring by default)",
                "Open items / data needed",
            ],
            "constraints": base_constraints + ["Do NOT assign risk scores unless provided by the system."],
            "style": ["Use a simple table-like format if helpful.", "Clearly label all entries as draft examples."],
        },
        "fmea": {
            "purpose": "FMEA: analyze potential failure modes, effects, causes, and draft risk prioritization fields.",
            "required_sections": [
                "Scope and assumptions",
                "Draft FMEA rows per component (example placeholders)",
                "Scoring guidance (placeholders; do not claim executed analysis)",
            ],
            "constraints": base_constraints + ["Do NOT fabricate verification results or approved controls."],
            "style": ["Prefer one row per component where possible.", "Mark placeholder failure modes/effects clearly as draft."],
        },
        "risk_controls_doc": {
            "purpose": "Risk Control Measures Documentation: list candidate controls and how they could be verified (planned).",
            "required_sections": [
                "Control strategy overview (inherent/protective/information)",
                "Draft controls grouped by component (placeholders)",
                "Planned verification methods (TBD; no execution claims)",
                "Effectiveness (placeholder)",
            ],
            "constraints": base_constraints,
            "style": ["Group by component where possible.", "Use structured bullets for each control."],
        },
        "design_inputs_doc": {
            "purpose": "Design Inputs Documentation: draft design input requirements derived from intended use, environment, and safety.",
            "required_sections": [
                "Assumptions",
                "Draft design inputs (use 'The device shall…' language)",
                "Traceability placeholders (to components/risks)",
            ],
            "constraints": base_constraints,
            "style": ["Use numbered requirements.", "Keep each requirement testable in principle, but allow TBD acceptance criteria."],
        },
        "design_outputs_doc": {
            "purpose": "Design Outputs Documentation: placeholder outputs mapped to design inputs for traceability scaffolding.",
            "required_sections": ["Draft output entries mapped to inputs", "Open items / to be defined"],
            "constraints": base_constraints,
            "style": ["Use a simple mapping table: Input → Output (placeholder)."],
        },
        "design_dev_plan": {
            "purpose": (
                "Design & Development Plan (ISO 13485 design control): planned activities, phases/gates, roles, deliverables, "
                "reviews, V&V alignment, risk management integration, and traceability — draft only."
            ),
            "required_sections": [
                "Purpose and scope (draft)",
                "Design phases (concept through transfer) with TBD placeholders for dates",
                "Roles and responsibilities (titles only; no invented person names)",
                "Design reviews and deliverables (examples; no approval claims)",
                "Risk management and traceability expectations (high level)",
                "Open items / TBD",
            ],
            "constraints": base_constraints
            + [
                "Do NOT fabricate signatures, approval dates, meeting minutes, or completed design reviews.",
                "Do NOT claim the design is complete, validated, or ready for release.",
                "Use only components and profile context provided; do not invent device-specific risks or requirements.",
            ],
            "style": ["Formal controlled-document tone.", "Bullets and numbered subsections.", "Explicit TBD where data is missing."],
        },
        "vv_plan": {
            "purpose": "Verification & Validation Plan: structured, high-level plan; activities remain 'Planned'.",
            "required_sections": ["Definitions (Verification vs Validation)", "Strategy overview", "Planned activities (placeholders)", "Traceability expectations"],
            "constraints": base_constraints,
            "style": ["Explicitly label activities as 'Planned'.", "Do not include detailed test procedures."],
        },
        "vv_evidence": {
            "purpose": "V&V Evidence Report: evidence slots for planned activities; default 'Not Executed'.",
            "required_sections": ["DRAFT — NOT EXECUTED banner", "Evidence slots (placeholders)", "Deviations/notes (empty placeholders)"],
            "constraints": base_constraints,
            "style": ["Keep each evidence slot short and structured."],
        },
        "validation_summary": {
            "purpose": "Validation Summary: high-level structure only; explicitly not complete until evidence exists.",
            "required_sections": ["NOT COMPLETE banner", "Intended use summary", "Validation approach (placeholder)", "Evidence summary (placeholder)", "Conclusions (must state not complete)"],
            "constraints": base_constraints,
            "style": ["Avoid conclusions; keep as structure and placeholders."],
        },
        "rmf": {
            "purpose": (
                "Risk Management File / Report: ISO 14971-oriented index pointing to authoritative SmartQS documents only "
                "(RMP, Hazard Analysis, FMEA, risk controls, residual evaluation, management review)."
            ),
            "required_sections": [
                "Draft banner / reference-only statement",
                "Purpose of the RMF as an index (not a duplicate hazard register)",
                "Traceability statement (by document identity and version)",
                "Section placeholders pointing to each authoritative record",
            ],
            "constraints": base_constraints
            + [
                "Do NOT invent hazards, failure modes, harms, severity/probability scores, or verification results.",
                "Do NOT claim approvals, completeness, or compliance.",
                "If project context does not include specific risks, use only generic ISO 14971 structure language.",
            ],
            "style": ["Short, audit-friendly sentences.", "Prefer bullets and explicit 'see linked document' wording."],
        },
        "benefit_risk_analysis": {
            "purpose": (
                "Benefit–Risk Analysis Report (ISO 14971): structured evaluation of whether overall residual risks "
                "are acceptable when weighed against anticipated clinical benefits."
            ),
            "required_sections": [
                "1. Document Information (project, device, RMF reference, version, date, author/reviewer/approver)",
                "2. Purpose",
                "3. Scope",
                "4. Reference Documents",
                "5. Device Overview (5.1 Device Description, 5.2 Intended Use, 5.3 Target Population)",
                "6. Summary of Residual Risks (6.1 Summary, 6.2 Top Residual Risks table, 6.3 Risk Control Effectiveness, 6.4 Overall Residual Risk Statement)",
                "7. Anticipated Clinical Benefits (7.1 Primary, 7.2 Secondary, 7.3 Quantification, 7.4 Time to Benefit)",
                "8. Benefit–Risk Comparison (8.1 Qualitative table, 8.2 Quantitative if applicable, 8.3 Key Considerations)",
                "9. State of the Art Comparison (9.1 Existing Alternatives, 9.2 Comparison table, 9.3 No-Treatment Scenario)",
                "10. Target Population Considerations (10.1 High-Risk Subpopulations, 10.2 Use Limitations)",
                "11. Uncertainty and Data Gaps",
                "12. Post-Market Surveillance Plan (12.1 Monitoring, 12.2 PMCF, 12.3 Reassessment Triggers)",
                "13. Overall Benefit–Risk Conclusion (13.1 Statement of Acceptability, 13.2 Conditions, 13.3 Determination Basis)",
                "14. Traceability table",
                "15. Approval table",
                "16. Revision History table",
            ],
            "constraints": base_constraints
            + [
                "Do NOT claim that benefits outweigh risks; provide a structured draft and state what evidence is missing.",
                "Do NOT fabricate clinical outcomes, complaint counts, adverse event rates, or comparative market data.",
                "Keep conclusions conditional (e.g., 'If the CER confirms X, then…').",
            ],
            "style": [
                "Use clear headings and short paragraphs matching the 16-section template.",
                "Include tables: Top Residual Risks (Hazard, Sequence of Events, Harm, Severity, Probability, Risk Control Measures, Residual Risk); Qualitative Comparison; State of the Art; Traceability; Approval; Revision History.",
                "Explicitly label any missing evidence as TBD / Not provided.",
            ],
        },
    }

    # Add compile-only docs with strict constraints.
    for t in compile_only:
        reg.setdefault(t, {})
        reg[t] = {
            "purpose": f"{t}: compile-only output in SmartQS (links/status compilation).",
            "required_sections": [
                "AI-GENERATED EXAMPLE — DRAFT ONLY",
                "Compilation note (authoritative content is compiled in SmartQS)",
                "Proposed structure (placeholders only)",
                "Open items / data needed",
            ],
            "constraints": base_constraints + _compile_only_constraints(),
            "style": ["Use placeholders and conditional language.", "Do not claim that artifacts exist."],
        }

    return reg

